export const MONTHS = [
  "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO",
  "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"
];

export const DEFAULT_ECONOMIC_ACTIVITIES = [
  "ADMINISTRATIVO OBRA",
  "ASEO",
  "CARPINTERIA MADERA",
  "CARPINTERIA METALICA",
  "CASINO",
  "CIMENTACION",
  "ENCHAPES",
  "ESTRUCTURA",
  "ESTUCO Y PINTURA",
  "IMPERMEABILIZACIÓN",
  "INSTALACIÓN DE ASCENSORES",
  "INSTALACIÓN DE EQUIPOS HIDROSANITARIOS Y RCI",
  "INSTALACIÓN DE SEGUIRDAD Y CONTROL",
  "INSTALACIONES ELÉCTRICAS INTERNAS",
  "INSTALACIONES HIDRAULICAS INTERNAS",
  "MAMPOSTERÍA",
  "MOVIMIENTO DE TIERRAS",
  "OPERATIVO OBRA",
  "OTRO",
  "PAISAJISMO",
  "PAÑETES",
  "PILOTAJE",
  "PRELIMINARES",
  "URBANISMO",
  "URBANISMO ELÉCTRICO",
  "URBANISMO HIDRÁULICO",
  "VENTANERIA",
  "VÍAS"
];

export const DEFAULT_DANGERS = [
  "BIOLÓGICO",
  "FÍSICO",
  "QUÍMICO",
  "PSICOSOCIAL",
  "BIOMECÁNICO",
  "MECÁNICO",
  "ELÉCTRICO",
  "LOCATIVO",
  "TECNOLÓGICO",
  "TRÁNSITO",
  "PÚBLICO",
  "ALTURAS",
  "CONFINADOS",
  "FENÓMENOS_NATURALES"
];

export const DANGER_DESCRIPTIONS: Record<string, string[]> = {
  "BIOLÓGICO": [
    "EXPOSICIÓN A VIRUS",
    "EXPOSICIÓN A BACTERIAS, HONGOS Y/O PARÁSITOS",
    "EXPOSICIÓN A PICADURAS",
    "EXPOSICIÓN A MORDEDURAS",
    "EXPOSICIÓN A FLUÍDOS O EXCREMENTOS"
  ],
  "FÍSICO": [
    "EXPOSICIÓN A RUÍDO",
    "EXPOSICIÓN A ILUMINACIÓN",
    "EXPOSICIÓN A VIBRACIÓN",
    "EXPOSICIÓN A TEMPERATURAS EXTREMAS",
    "EXPOSICIÓN A PRESIÓN ATMOSFÉRICA",
    "EXPOSICIÓN A RADIACIONES IONIZANTES",
    "EXPOSICIÓN A RADIACIONES NO IONIZANTES"
  ],
  "QUÍMICO": [
    "EXPOSICIÓN A POLVOS",
    "EXPOSICIÓN A FIBRAS",
    "EXPOSICIÓN A SUSTANCIAS QUÍMICAS",
    "EXPOSICIÓN A GASES Y VAPORES",
    "EXPOSICIÓN A HUMOS",
    "EXPOSICIÓN A MATERIAL PARTICULADO"
  ],
  "PSICOSOCIAL": [
    "GESTIÓN ORGANIZACIONAL",
    "CARACTERÍSTICAS DE LA ORGANIZACIÓN DEL TRABAJO",
    "CARACTERÍSTICAS DEL GRUPO SOCIAL DE TRABAJO",
    "CONDICIONES DE LA TAREA",
    "INTERFASE PERSONA TAREA",
    "JORNADA DE TRABAJO"
  ],
  "BIOMECÁNICO": [
    "POSTURA PROLONGADA O MANTENIDA",
    "SOBREESFUERZO",
    "MOVIMIENTO REPETITIVO",
    "MANIPULACIÓN MANUAL DE CARGAS"
  ],
  "MECÁNICO": [
    "PROYECCIÓN DE PARTÍCULAS",
    "USO DE EQUIPOS",
    "USO DE HERRAMIENTAS",
    "MANIPULACIÓN DE MATERIALES",
    "EXPOSICIÓN A MAQUINARIA EN MOVIMIENTO",
    "EXPOSICIÓN A MAQUINARIA con PARTES EN MOVIMIENTO",
    "IZAJE DE CARGAS"
  ],
  "ELÉCTRICO": [
    "EXPOSICIÓN A BAJA TENSIÓN",
    "EXPOSICIÓN A MEDIA TENSIÓN",
    "EXPOSICIÓN A ALTA TENSIÓN",
    "EXPOSICIÓN A ESTÁTICA"
  ],
  "LOCATIVO": [
    "SUPERFICIE DE TRABAJO Y/O TRÁNSITO",
    "INSTALACIONES LOCATIVAS",
    "CAÍDA DE OBJETOS",
    "ALMACENAMIENTO DE MATERIALES, EQUIPOS Y/O HERRAMIENTAS",
    "EQUIPOS DE OFICINA",
    "CONDICIONES DE ORDEN Y ASEO"
  ],
  "TECNOLÓGICO": [
    "EXPOSICIÓN A EXPLOSIONES",
    "EXPOSICIÓN A FUGAS",
    "EXPOSICIÓN A DERRAMES",
    "EXPOSICIÓN A INCENDIOS"
  ],
  "TRÁNSITO": [
    "EXPOSICIÓN A CHOQUES CON VEHÍCULOS",
    "ATROPELLAMIENTOS"
  ],
  "PÚBLICO": [
    "ORDEN PÚBLICO (ROBOS, ATRACOS, ASALTOS, DESORDEN PÚBLICO, ETC.)"
  ],
  "ALTURAS": [
    "TRABAJO EN ALTURAS"
  ],
  "CONFINADOS": [
    "TRABAJOS EN ESPACIOS CONFINADOS"
  ],
  "FENÓMENOS_NATURALES": [
    "EXPOSICIÓN A SISMO Y/O TERREMOTO",
    "EXPOSICIÓN A INUNDACIONES",
    "EXPOSICIÓN A PRECIPITACIONES (LLUVIAS, GRANIZADAS, HELADAS)"
  ]
};

export const PRIORITY_CLASS_MAP: Record<string, string> = {
  "INMEDIATA": "I",
  "URGENTE": "A",
  "PRONTA": "B",
  "POSTERIOR": "C"
};
